name: Deploy Productcore

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_product_core:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Restart App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/ALT-EXAM
            git pull origin main
            npm install
            pm2 restart 0
